openapi: 3.0.1
info:
  title: Comments API
  description: API for retrieving comments with configurable authentication
  version: 1.0.0
servers:
  - url: https://la952on1vc.execute-api.ap-northeast-3.amazonaws.com/{env}
    variables:
      env:
        default: dev
        description: API Gateway stage
paths:
  /comment:
    options:
      summary: CORS support
      description: Enable CORS by returning correct headers
      responses:
        '200':
          description: CORS enabled
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content: {}
    get:
      summary: Get comments
      description: Retrieves comments
      parameters:
        - name: comment_id
          in: query
          description: ID of the comment to retrieve
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  comments:
                    type: array
                    items:
                      $ref: '#/components/schemas/Comment'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Comment not found
components:
  parameters:
    CORSHeader:
      name: Access-Control-Allow-Origin
      in: header
      required: true
      description: Header to allow access API endpoint from the server
      schema:
        type: string
        example: "http://127.0.0.1"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Comment:
      title: Comment object
      description: Comment data from the Blog and Post application
      type: object
      properties:
        id:
          type: string
        content:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        __typename:
          type: string